# Generated by Django 6.0.4 on 2026-04-28 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Package Name')),
                ('category', models.CharField(choices=[('facials', 'Facials'), ('foodstuffs', 'Foodstuffs'), ('phone', 'Phone & Accessories'), ('breakfast', 'Breakfast')], max_length=20, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description')),
                ('items', models.JSONField(verbose_name='Items Included')),
                ('image_url', models.URLField(verbose_name='Product Image URL')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Regular Price (GH₵)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Package',
                'verbose_name_plural': 'Product Packages',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_location', models.CharField(max_length=300, verbose_name='Delivery Location')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('cash_on_delivery', 'Cash on Delivery')], max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('student_discount_applied', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, verbose_name='Order Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.package')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.ManyToManyField(related_name='orders', through='store.OrderItem', to='store.package'),
        ),
    ]
